# Generated by Django 4.2 on 2025-08-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chronic_conditions",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="height",
            field=models.FloatField(blank=True, help_text="Height in cm", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="medical_conditions",
            field=models.TextField(blank=True, help_text="Medical conditions"),
        ),
        migrations.AddField(
            model_name="user",
            name="weight",
            field=models.FloatField(blank=True, help_text="Weight in kg", null=True),
        ),
    ]
