# Generated by Django 4.2 on 2025-08-14 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0002_remove_user_chronic_conditions_user_age_user_height_and_more",
        ),
    ]

    operations = []
